# Generated by Django 6.0.6 on 2026-07-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='year_of_study',
            field=models.PositiveIntegerField(),
        ),
    ]
